feat api_data and api_client : accountant add a category
WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-2-Team-D pull request #87
Opened 2024-12-05 15:00 UTC by Ludovicscelles

feat api_data and api_client : as a accountant to add a category

2024-12-05 15:04 UTC, Ludovicscelles commented
![image](https://github.com/user-attachments/assets/623de79a-73b8-4269-b202-52249ff03526)
![image](https://github.com/user-attachments/assets/3870eb6e-398f-487e-b6c0-fe335fbeab14)

2024-12-05 15:12 UTC, feub approved these changes
Par contre, tu n'as pas du tout de class-validator dans le resolver pour vérifier que le label est valide

2024-12-05 15:13 UTC, Gadln approved these changes

2024-12-05 15:14 UTC, pjroggy requested changes

2024-12-05 15:14 UTC, pjroggy commented on api_data/src/category/category.entity.ts
> +  id!: number;
still usefull?

2024-12-05 15:14 UTC, pjroggy commented on client/src/pages/accountant/category/ManageCategory.tsx
> +    <section>
replace by fragment

2024-12-05 16:27 UTC, Gadln approved these changes

2024-12-05 20:11 UTC, Gadln approved these changes

2024-12-06 07:50 UTC, pjroggy approved these changes

2024-12-06 08:09 UTC, merged